# base image
FROM mhart/alpine-node:latest

# exclude npm cache from the image
VOLUME /root/.npm

# add files ad set workdir
COPY . /wsdlrdr
WORKDIR /wsdlrdr

# install dependecys, but first set oberon as registry archive
RUN npm install

#launch dev environment
CMD npm t
